backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "home_id"
    label: "Homepage (Indonesia)"
    folder: "content"
    create: false
    extension: "md"
    format: "frontmatter"
    identifier_field: "title"
    filter:
      field: "lang"
      value: "id"
    fields:
      - { label: "Bahasa", name: "lang", widget: "hidden", default: "id" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "home_en"
    label: "Homepage (English)"
    folder: "content"
    create: false
    extension: "md"
    format: "frontmatter"
    identifier_field: "title"
    filter:
      field: "lang"
      value: "en"
    fields:
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
