backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  # Bahasa Indonesia
  - name: "home_id"
    label: "Homepage (ID)"
    folder: "content/id"
    create: false
    slug: "home"
    extension: "md"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Subjudul", name: "subtitle", widget: "string" }
      - { label: "CTA", name: "cta", widget: "string" }

  # Bahasa Inggris
  - name: "home_en"
    label: "Homepage (EN)"
    folder: "content/en"
    create: false
    slug: "home"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "CTA", name: "cta", widget: "string" }
